## Label Encodeing, One Hot Encoding, Bag Of Words, TF-IDF, Word Embeddings
### label and one hot uses lots of spaces

# Bag Of Words

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('spam.csv')
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
df['Category'].value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [6]:
def get_spam_number(x):
    if x == 'spam':
        return 1
    else:
        return 0

In [7]:
# spam 1 and other 0
df['spam'] = df['Category'].apply(lambda x:1 if x =='spam' else 0)

In [8]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df['Message'], df['spam'], test_size=0.2)

In [11]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((4457,), (1115,), (4457,), (1115,))

In [13]:
type(X_train)

pandas.core.series.Series

In [14]:
from sklearn.feature_extraction.text import CountVectorizer

In [15]:
v = CountVectorizer()

In [16]:
X_train.values

array(['Alright i have a new goal now',
       'Oic... I saw him too but i tot he din c me... I found a group liao...',
       'Santa Calling! Would your little ones like a call from Santa Xmas eve? Call 09058094583 to book your time.',
       ...,
       'Horrible gal. Me in sch doing some stuff. How come u got mc?',
       'Even if he my friend he is a priest call him now',
       'Did u receive my msg?'], dtype=object)

In [19]:
X_train_cv = v.fit_transform(X_train)

In [23]:
type(X_train_cv)

scipy.sparse._csr.csr_matrix

In [25]:
X_train_cv.toarray()[500:600]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [28]:
v.get_feature_names_out()[1000:1050]

array(['anythingtomorrow', 'anytime', 'anyway', 'anyways', 'anywhere',
       'aom', 'apart', 'apartment', 'apes', 'apeshit', 'aphex', 'apnt',
       'apo', 'apologetic', 'apologise', 'apologize', 'apology', 'app',
       'apparently', 'appear', 'appendix', 'applausestore', 'applebees',
       'apply', 'applyed', 'appointment', 'appointments', 'appreciate',
       'appreciated', 'approaches', 'approaching', 'appropriate',
       'approve', 'approved', 'approx', 'apps', 'appt', 'appy', 'april',
       'aproach', 'apt', 'aptitude', 'aquarius', 'ar', 'arab', 'arabian',
       'arcade', 'archive', 'ard', 'are'], dtype=object)

In [29]:
X_train_cv.shape

(4457, 7789)

In [30]:
v.get_feature_names_out().shape

(7789,)

In [31]:
dir(v)

['_CountVectorizer__metadata_request__fit',
 '_CountVectorizer__metadata_request__transform',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__sklearn_tags__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_params_html',
 '_html_repr',
 '_limit_features',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr

In [35]:
v.vocabulary_ # it's position of word

{'alright': 924,
 'have': 3371,
 'new': 4788,
 'goal': 3172,
 'now': 4867,
 'oic': 4936,
 'saw': 5953,
 'him': 3450,
 'too': 7009,
 'but': 1591,
 'tot': 7029,
 'he': 3382,
 'din': 2333,
 'me': 4426,
 'found': 2975,
 'group': 3261,
 'liao': 4115,
 'santa': 5927,
 'calling': 1631,
 'would': 7652,
 'your': 7752,
 'little': 4171,
 'ones': 4965,
 'like': 4133,
 'call': 1618,
 'from': 3029,
 'xmas': 7692,
 'eve': 2670,
 '09058094583': 180,
 'to': 6972,
 'book': 1435,
 'time': 6939,
 'da': 2147,
 'am': 934,
 'waiting': 7392,
 'for': 2951,
 'sad': 5897,
 'story': 6526,
 'of': 4917,
 'man': 4359,
 'last': 4044,
 'week': 7475,
 'was': 7428,
 'my': 4696,
 'day': 2188,
 'wife': 7550,
 'did': 2311,
 'nt': 4871,
 'wish': 7581,
 'parents': 5104,
 'forgot': 2961,
 'so': 6300,
 'kids': 3951,
 'went': 7496,
 'work': 7633,
 'even': 2672,
 'colleagues': 1899,
 'not': 4856,
 'as': 1086,
 'entered': 2623,
 'cabin': 1607,
 'pa': 5068,
 'said': 5905,
 'happy': 3350,
 'boss': 1451,
 'felt': 2827,
 'special': 6

In [36]:
v.get_feature_names_out()[7692]

'xmas'

In [37]:
X_train_np = X_train_cv.toarray()
X_train_np[4:8]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [38]:
np.where(X_train_np[0] != 0)

(array([ 924, 3172, 3371, 4788, 4867]),)

In [39]:
from sklearn.naive_bayes import MultinomialNB

In [40]:
model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [42]:
X_test_cv = v.transform(X_test)

In [43]:
X_test_cv.shape

(1115, 7789)

In [44]:
model.score(X_test_cv, y_test)

0.9865470852017937

In [46]:
from sklearn.metrics import classification_report

In [47]:
y_pred = model.predict(X_test_cv)

In [48]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       953
           1       0.98      0.93      0.95       162

    accuracy                           0.99      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [49]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]


In [50]:
emails_cv = v.transform(emails)

In [51]:
model.predict(emails_cv)

array([0, 1])